name: postbin_local_deployment
services:
  postgres:
    image: postgres:15.5-alpine
    container_name: postbin
    environment:
      POSTGRES_DB: postbin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
    ports:
      - "5433:5432"
    networks:
      - postbin_network

  spring:
    image: postbin
    container_name: spring_container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - postbin_network
    environment:
      SPRING_PROFILES_ACTIVE: local

networks:
  postbin_network:

