spring:
  application:
    name: postbin
  datasource:
    url: jdbc:postgresql://localhost:5432/postbin
    username: ${USERNAME_DB}
    password: ${PSW_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  liquibase:
    change-log: 'db/changelog/liquibase-changelog.xml'
    show-summary-output: all
  messages:
    basename: ValidationMessages
logging:
  level:
    root: trace
    org.springframework: trace