spring:
  application:
    name: postbin
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  liquibase:
    change-log: 'db/changelog/liquibase-changelog.xml'
    show-summary-output: all
  messages:
    basename: ValidationMessages