spring:
  application:
    name: postbin
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/postbin
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  liquibase:
    change-log: 'db/changelog/liquibase-changelog.xml'
    show-summary-output: all
server:
  port: 8080